### ISSUE TITLE
Commands in README.md

### ISSUE THREAD

**Issue by baldore** [toomastahves/react-starter#1]
Hi, I have a question about your project. Do I have to run each command in the Command-line to have each functionality? If that's the case, I recommend you to add those commands as scripts in package.json. Otherwise, each time somebody uses your repository, he/she are gonna need to install each dependency globally. Thanks!

**Comment by toomastahves** [comment]
Hey, thanks for feedback. To install all needed dependencies only 'npm install' is enough.

Updated README.md and removed confusing text.

**Comment by baldore** [comment]
Nice!!! keep going dude!
